server {
    listen 80;
    
    # Proxy da API
    location /api/ {
        proxy_pass http://back:8080/;
    }
    
    # Angular
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}